### ISSUE TITLE
vacatures dark mode styling

### ISSUE THREAD

**Issue by jerzy-vletter** [petersnoek/stagespeeddate#32]
naam van bedrijf wordt niet naar darkmode gezet als je darkmode aanklikt links bovenin

**Comment by joshuaroovers** [comment]
darkmode toggle is weg gehaald in devBugs4/release 0.5

**Comment by jerzy-vletter** [comment]
deze bug is niet opgelost, maar wij hadden ivm het doel van de applicatie en de tijd die wij hadden besloten om deze functionaliteit uit te zetten, mocht iemand hier nog aan gaan werken kijk niet in de commit die hieraan is gekoppeld want die heeft er vrij weinig mee te maken.
