### ISSUE TITLE
side bar missing pages when on the update your credentials page

### ISSUE THREAD

**Issue by jerzy-vletter** [petersnoek/stagespeeddate#40]
discovered in release 0.4

current status inactive, we are aware of the problem but have not gotten the time to look at why it is a problem, if we do get the time to look at it the status will be updated with the cause of the problem hopefully included.

**Comment by LeviHoevers** [comment]
bug has been fixed on branch issue_40, there was a if statement check for the student role that prevented the sidebar from showing any other navbar item than the ones meant for the student. i removed the if statement and the problem was resolved
